version: '3'

services:
  kadira-db:
    image: mongo:latest
    command:
      - --storageEngine=wiredTiger
    volumes:
      - data:/data/db
    ports:
      - "27017:27017"
  kadira-engine:
    build: ./kadira-engine
    ports:
      - "10001:80"
    environment:
      - PORT=80
      - MONGO_SHARD_URL_one=mongodb://kadira-db:27017/apm
      - MONGO_URL=mongodb://kadira-db:27017/apm
    links:
      - kadira-db
    restart: always
  kadira-api:
    build: ./kadira-api
    ports:
      - "10002:80"
    environment:
      - PORT=80
      - MONGO_APP_URL=mongodb://kadira-db:27017/apm
      - MONGO_SHARD_URL_one=mongodb://kadira-db:27017/apm
      - MAIL_URL=smtp://user:pass@smtp.mailgun.org:587
      - AUTH_SECRET=secret
      - JWT_SECRET=secret
      - JWT_LIFETIME=1d
    links:
      - kadira-db
    restart: always
  kadira-ui:
    build: ./kadira-ui
    ports:
      - "10003:80"
    environment:
      - PORT=80
      - ROOT_URL=http://127.0.0.1:10003
      - MONGO_URL=mongodb://kadira-db:27017/apm
      - MONGO_SHARD_URL_one=mongodb://kadira-db:27017/apm
      - MAIL_URL=smtp://user:pass@smtp.mailgun.org:587
      - AWS_ACCESS_KEY_ID=xxxxxxxxxxxxx
      - AWS_SECRET_ACCESS_KEY=xxxxxxxxxxxxx
      - METEOR_SETTINGS={"public":{"tender":{"key":"405871e6-4816-4d44-a0f3-860c0e988078"},"intercom":{},"loginState":{"domain":"","cookieName":"kadira-dev-login-state"}},"tender":{"secret":"71825e70-d11d-489b-b273-2afdca024fd6"},"stripe":{"amol":{"apiKey":"sk_test_tNO29lr3TPEvetcJfB4Vf54s","publishableKey":"pk_test_ZlbObLXALEa5wwBShlBitOS3","appName":"Kadira","appLogo":"https://kadira.io/favicon.ico"},"kadirahq":{"apiKey":"sk_test_22QITCBPhqEaEKjHXK5BBwO8","publishableKey":"pk_test_Tc1iVNRP9p8o7zgYWoWjZnm4","appName":"KadiraHQ","appLogo":"https://kadira.io/favicon.ico"}}}
    links:
      - kadira-db
  kadira-rma:
    build: ./kadira-rma
    environment:
      - MONGO_SHARD=one
      - MONGO_URL=mongodb://kadira-db:27017/apm
    links:
      - kadira-db
volumes:
  data: